"""add_customer_whatsapp_opt_in

Revision ID: 663ba4145b00
Revises: 8506dffe0eb1
Create Date: 2026-08-02 18:15:19.075672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '663ba4145b00'
down_revision: Union[str, Sequence[str], None] = '8506dffe0eb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('whatsapp_opt_in', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('customers', sa.Column('whatsapp_opt_in_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'whatsapp_opt_in_at')
    op.drop_column('customers', 'whatsapp_opt_in')
    # ### end Alembic commands ###
